FROM linuxserver/code-server:latest
RUN apt-get update \
    && apt-get install -y apt-transport-https ca-certificates curl gnupg lsb-release \
    && curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg \
    && echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null \
    && apt-get update \
    && apt-get install -y docker-ce docker-ce-cli containerd.io
ENV DOCKER_TLS_CERTDIR=/certs
COPY --from=docker:dind /usr/local/bin/docker /usr/local/bin/docker
COPY --from=docker:dind /usr/local/bin/dockerd /usr/local/bin/dockerd
COPY --from=docker:dind /usr/local/bin/containerd /usr/local/bin/containerd
COPY --from=docker:dind /usr/local/bin/docker-init /usr/local/bin/docker-init
EXPOSE 8443 2375
ENTRYPOINT ["docker-entrypoint.sh"]
CMD ["code-server", "dind"]
RUN echo "alias 'docker run -it hashicorp/terraform'='terraform'" >> ~/.bashrc
